BASE: ['']
TOOLBOX_MODE: 'train_and_test'      # "train_and_test"  or "only_test"
TASK: 'bvp'
DATASET_TYPE: 'face'
TRAIN:
  USE_PRETRAINED_WEIGHTS: true
  BATCH_SIZE: 16
  EPOCHS: 50
  

  LR: 9e-3
  MODEL_FILE_NAME: Our_1818FCA++
  PLOT_LOSSES_AND_LR: true
  DATA:
    INFO: 
      STATE: [1, 3, 4, 5]
      TYPE: [1] # 1 - face, 2 - finger
    DATASET_TYPE: 'face'  #['face', 'finger', 'both'] 
    FS: 30
    DATASET: Spo22
    DO_PREPROCESS: false           # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "D:\\spo2"                    # Raw dataset path, need to be updated
    CACHED_PATH: "D:\\proc_spo2"     # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: 'DiffNormalized'
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: false
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: false
          DYNAMIC_DETECTION_FREQUENCY: 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    INFO: 
      STATE: [1, 3, 4, 5]
      TYPE: [1] # 1 - face, 2 - finger
    DATASET_TYPE: 'face'  #['face', 'finger', 'both'] 
    FS: 30
    DATASET: Spo22
    DO_PREPROCESS: false           # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "D:\\spo2"                    # Raw dataset path, need to be updated
    CACHED_PATH: "D:\\proc_spo2"     # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.6
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: 'DiffNormalized'
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: false
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: false
          DYNAMIC_DETECTION_FREQUENCY: 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson','SNR']
  USE_LAST_EPOCH: True
  DATA:
    INFO: 
      STATE: [1, 3, 4, 5]
      TYPE: [1] # 1 - face, 2 - finger
    DATASET_TYPE: 'face'  #['face', 'finger', 'both'] 
    FS: 30
    DATASET: Spo22
    DO_PREPROCESS: false           # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "D:\\spo2"                    # Raw dataset path, need to be updated
    CACHED_PATH: "D:\\proc_spo2"     # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: 'DiffNormalized'
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: false
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: false
          DYNAMIC_DETECTION_FREQUENCY: 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/bvp_train
MODEL:
  DROP_RATE: 0.2
  NAME: FCA    ## MultiPhysNet , My , Muti , My_Mae , MultiPhysNet128 
  My:
    FRAME_NUM: 128
INFERENCE:
  BATCH_SIZE: 16
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: "D:\\SUMS-main\\SUMS-main\\rppg-Toolbox_SUMS\\runs\\bvp_train\\Spo22_SizeW72_SizeH72_ClipLength128_DataTypeDiffNormalized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_BackendHC_Large_boxFalse_Large_size1.5_Dyamic_DetFalse_det_len32_Median_face_boxFalse\\PreTrainedModels\\FCA_Our_PURE_Epoch6.pth"
  
